#!/bin/bash

if [ -z "$1" ] ; then
	exit 1
fi

APTLY="aptly --config ./conf/aptly.conf"

TGT="./zfs-chroot"
export TGT

if [ -d "$TGT" ] ; then
	umount -f $TGT/proc
	umount -f $TGT/sys
	rm -rf $TGT
fi

# Make sure the truenas target exists
ln -fs /usr/share/debootstrap/scripts/bullseye /usr/share/debootstrap/scripts/truenas

# Bootstrap the zfs chroot
debootstrap truenas $TGT file:///srv/aptly-publish/truenas/unstable
if [ $? -ne 0 ] ; then exit 1; fi

# Make the chroot ready to build
mount proc $TGT/proc -t proc
if [ $? -ne 0 ] ; then exit 1; fi
mount sysfs $TGT/sys -t sysfs
if [ $? -ne 0 ] ; then exit 1; fi
cp /etc/hosts $TGT/etc/hosts

# Get ZFS Module Name
ZFSPKG=$(ls /srv/aptly-publish/truenas/unstable/pool/main/z/zfs-dkms-bin/zfs-modules*)
ZFSDEB=$(basename $ZFSPKG | cut -d '_' -f 1)

# Setup the apt repo
echo "deb http://127.0.0.1/truenas/unstable/ truenas main" > ${TGT}/etc/apt/sources.list

chroot ${TGT} apt update
if [ $? -ne 0 ] ; then exit 1; fi

chroot ${TGT} apt install -y locales
if [ $? -ne 0 ] ; then exit 1; fi
chroot ${TGT} apt install -y ${ZFSDEB} zfsutils-linux gdisk
if [ $? -ne 0 ] ; then exit 1; fi

LIBZFS=$(cd ${TGT} && ls ./usr/lib/libzfs*)
LIBNV=$(cd ${TGT} && ls ./usr/lib/libnv* ./usr/lib/libuu* ./lib/x86_64-linux-gnu/libpopt* ./lib/x86_64-linux-gnu/libstdc++* ./lib/x86_64-linux-gnu/libgcc*)
MODS=$(cd ${TGT} && ls ./lib/modules/)

# Create tarball to extract into initrd
tar cvf - -C ${TGT} ./usr/sbin/zfs \
	./usr/sbin/zpool \
	./usr/sbin/zdb \
	./usr/sbin/sgdisk \
	${LIBZFS} \
	${LIBNV} \
	./lib/modules/${MODS}/updates/dkms |
	tar xf - -C "${1}"

# Cleanup the chroot
umount -f $TGT/proc
umount -f $TGT/sys

# Cleanup
rm -rf $TGT
