#!/bin/sh

DEBMIRROR=/srv/mirror/debian
DEBTARGET=bullseye

TNMIRROR=/srv/mirror/truenas
TNTARGET=bullseye-truenas-unstable

# Create the local dists directory with contents from the TrueNAS mirror
rm -rf  ${DEBMIRROR}/dists/${DEBTARGET}/local
cp -r ${TNMIRROR}/dists/${TNTARGET}/main ${DEBMIRROR}/dists/${DEBTARGET}/local

while read distdir
do
	if [ ! -d "${TNMIRROR}/pool/main/${distdir}" ] ; then
		echo "WARNING: Missing ${distdir} package directory"
		continue
	fi
	if [ -d "${DEBMIRROR}/pool/main/${distdir}" ] ; then
		echo "Cleanup: ${DEBMIRROR}/pool/main/${distdir}"
		rm -rf "${DEBMIRROR}/pool/main/${distdir}"
	fi
	mkdir -p ${DEBMIRROR}/pool/main/${distdir}
	cp -r ${TNMIRROR}/pool/main/${distdir}/* ${DEBMIRROR}/pool/main/${distdir}/
done < conf/dist-pkgs

# Build the Packages.gz
../tools/Packages-gen $DEBTARGET amd64

gpg --list-keys | grep -q truenas-cd
if [ $? -ne 0 ] ; then
	gpg --quick-generate-key --batch --pinentry-mode loopback --yes --passphrase '' truenas-cd@localhost
	gpg --armor --export truenas-cd@localhost | apt-key add -
fi

# Rebuild the Release and InRelease files
cd ${DEBMIRROR}/dists/${DEBTARGET}
apt-ftparchive  --md5 --sha256 release .  > Release
if [ $? -ne 0 ] ; then
	echo "Failed running apt-ftparchive"
	exit 1
fi
rm Release.gpg
gpg --default-key truenas-cd@localhost --armor --output Release.gpg --detach-sign Release
if [ $? -ne 0 ] ; then
	echo "Failed signing Release"
	exit 1
fi
rm InRelease
gpg --default-key truenas-cd@localhost --clearsign --output InRelease Release
if [ $? -ne 0 ] ; then
	echo "Failed signing InRelease"
	exit 1
fi

# Export the key we just re-signed with so it can be used on ISO repo
gpg --armor --export truenas-cd@localhost > conf/truenas-repo-key.gpg
